version: "3.8"
services:
  db:
    image: mariadb:10.3.0
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASS}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASS}"
    networks:
      - app-network
  _phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.1.1
    restart: always
    ports:
      - "8082:80"
    depends_on:
      - db
    networks:
      - app-network
  backend:
    build: ./server
    environment:
      DB_HOST: db
      DB_PORT: "${DB_PORT}"
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASS}"
      DB_NAME: "${DB_NAME}"
      NODE_ENV: production
    ports:
      - "3005:3005"
    depends_on:
      - db
    networks:
      - app-network
    command: npm run start
networks:
  app-network:
    driver: bridge
